# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mariage',
            name='categorie',
            field=models.IntegerField(choices=[('ACTE DE NAISSANCES', (('normal', 'NORMAL'), ('mariage', 'EN VUE DE MARIAGE'), ('copie', 'COPIE INTEGRALE / JUGEMENT SUPPLETIF'))), ('acte_mariage', 'ACTE DE MARIAGE'), ('acte_mariage', 'ACTE DE DECES')], verbose_name='Type de Document'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='categorie',
            field=models.IntegerField(choices=[('ACTE DE NAISSANCES', (('normal', 'NORMAL'), ('mariage', 'EN VUE DE MARIAGE'), ('copie', 'COPIE INTEGRALE / JUGEMENT SUPPLETIF'))), ('acte_mariage', 'ACTE DE MARIAGE'), ('acte_mariage', 'ACTE DE DECES')], verbose_name='Type de Document'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='pere',
            field=models.CharField(blank=True, max_length=250, verbose_name='Nom et Pr\xe9noms du Pere'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='profession_pere',
            field=models.CharField(blank=True, max_length=250, verbose_name='Profession du Pere'),
        ),
    ]
