# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraits', '0002_auto_20180524_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naissance',
            name='categorie',
            field=models.IntegerField(choices=[('ACTE DE NAISSANCES', (('normal', 'NORMAL'), ('mariage', 'EN VUE DE MARIAGE'), ('copie', 'COPIE INTEGRALE / JUGEMENT SUPPLETIF'))), ('acte_mariage', 'ACTE DE MARIAGE'), ('acte_mariage', 'ACTE DE DECES')], verbose_name='Nature Document'),
        ),
    ]
